#nginxadmin-argo-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-argo-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "events","secrets"]
    #verbs: ["get", "list", "watch", "create", "update", "patch"]
  verbs: ["get", "list", "watch"]

    #- apiGroups: ["apps"]
    #  resources: ["deployments"]
    #  verbs: ["get", "list", "watch", "create", "update", "patch"]

- apiGroups: ["argoproj.io"]
  resources: ["applications","appprojects","applicationsets"]
  verbs: ["get","list","watch","update","patch","create"]

- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]

